# Generated by Django 4.2 on 2023-06-24 13:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='technology')),
            ],
        ),
        migrations.CreateModel(
            name='VacancyJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full name')),
                ('purpose', models.CharField(max_length=1000, verbose_name='Purpose')),
                ('region', models.CharField(max_length=100, verbose_name='Region')),
                ('contact', models.CharField(help_text='Telefon raqam va telegram linkni qoldiring.', max_length=200, verbose_name='Contact')),
                ('portfolio', models.FileField(blank=True, null=True, upload_to='', verbose_name='Portfolio link')),
                ('technology', models.ManyToManyField(to='vacancy.technology', verbose_name='Technology')),
            ],
            options={
                'verbose_name': 'Vacancy job',
                'verbose_name_plural': 'Vacancy jobs',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=150, null=True, verbose_name='company')),
                ('age', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None, verbose_name='ages [from, to]')),
                ('work_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='work time')),
                ('additional_info', models.CharField(blank=True, max_length=1000, null=True, verbose_name='additional information')),
                ('work_type', models.CharField(choices=[('internship', 'amaliyot'), ('work', 'ish')], default='internship', max_length=15, verbose_name='work type')),
                ('salary', models.CharField(blank=True, max_length=50, null=True, verbose_name='salary')),
                ('districts', models.CharField(choices=[('1', 'Bektimer tumani'), ('2', 'M.Ulug‘bek tumani'), ('3', 'Mirobod tumani'), ('4', 'Olmazor tumani'), ('5', 'Sergeli tumani'), ('6', 'Uchtepa tumani'), ('7', 'Yashnobod tumani'), ('8', 'Chilonzor tumani'), ('9', 'Shayxontohur tumani'), ('10', 'Yunusobod tumani'), ('11', 'Yakkasaroy tumani')], default='10', max_length=50, verbose_name='salary')),
                ('is_student', models.BooleanField(default=False, verbose_name='is student')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='username')),
                ('apply_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='apply time')),
                ('is_available', models.BooleanField(default=True, verbose_name='is available')),
                ('technologies', models.ManyToManyField(to='vacancy.technology', verbose_name='technologies')),
            ],
            options={
                'verbose_name': 'vacancy',
                'verbose_name_plural': 'vacancies',
            },
        ),
    ]
